// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9-HsHemNe5vyHrjy04H6qmSREInxl_0',
    appId: '1:678875072626:web:04117fa06e242ea7851aeb',
    messagingSenderId: '678875072626',
    projectId: 'stepcounter-95b83',
    authDomain: 'stepcounter-95b83.firebaseapp.com',
    storageBucket: 'stepcounter-95b83.firebasestorage.app',
    measurementId: 'G-KE167SPP03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw31QbGvPqrj4xhPiHdkUG1_CJsVDiA3E',
    appId: '1:678875072626:android:1253af3800700894851aeb',
    messagingSenderId: '678875072626',
    projectId: 'stepcounter-95b83',
    storageBucket: 'stepcounter-95b83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOQBS-DtowzooD4nhC76EpG6m1cgtoe8',
    appId: '1:678875072626:ios:4988a8fd554e4cb7851aeb',
    messagingSenderId: '678875072626',
    projectId: 'stepcounter-95b83',
    storageBucket: 'stepcounter-95b83.firebasestorage.app',
    iosBundleId: 'com.example.stepCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOQBS-DtowzooD4nhC76EpG6m1cgtoe8',
    appId: '1:678875072626:ios:4988a8fd554e4cb7851aeb',
    messagingSenderId: '678875072626',
    projectId: 'stepcounter-95b83',
    storageBucket: 'stepcounter-95b83.firebasestorage.app',
    iosBundleId: 'com.example.stepCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm9-HsHemNe5vyHrjy04H6qmSREInxl_0',
    appId: '1:678875072626:web:0103f57fc375c6bd851aeb',
    messagingSenderId: '678875072626',
    projectId: 'stepcounter-95b83',
    authDomain: 'stepcounter-95b83.firebaseapp.com',
    storageBucket: 'stepcounter-95b83.firebasestorage.app',
    measurementId: 'G-9JV99LEWPD',
  );

}